fun main() {
    repeat(3){
        println("Hi")
    }
    println()
    repeat(5){
        println("Kucing")
    }
    println()
    repeat(3){
        println("Hamster")
    }
    println()
    repeat(5){
        println("Pagi")
    }
    println()
    repeat(3){
        println("Malam")
    }
}